name: GraalVM build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      # See 'Options' for more details
          distribution: 'graalvm' # See 'Supported distributions' for available options
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build using Gradle # https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html
        working-directory: ./01-wc-tool
        run: ./gradlew nativeCompile
      - name: Publish Build
        uses: actions/upload-artifact@v4
        with:
          name: ccwc
          path: 01-wc-tool/build/native/nativeCompile/ccwc
